language: cpp

compiler:
  - gcc
  
before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi

install:
  # g++4.9
  - if [ "$CXX" = "g++" ]; then sudo apt-get install build-essential; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

notifications:
  email: false

os:
  - linux
