language: cpp

compiler:
  - gcc
  
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo apt-add-repository ppa:libccd-debs --yes
  - sudo apt-add-repository ppa:fcl-debs --yes
  - sudo apt-add-repository ppa:dartsim --yes
  - sudo apt-get update

install:
  # g++4.9
  - if [ "$CXX" = "g++" ]; then sudo apt-get install build-essential; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - sudo apt-get install libboost-dev
  - sudo apt-get install libpopt-dev
  - sudo apt-get install libtinyxml2-dev
  
build: make

notifications:
  email: false

os:
  - linux
