language: cpp

compiler:
  - g++
  
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install libpopt-dev libtinyxml2-dev libboost1.55-all-dev; fi

notifications:
  email: false
  
os:
  - linux
