language: cpp

compiler:
  - gcc
  
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo add-apt-repository ppa:apokluda/boost1.55 --yes
  - sudo apt-get update

install:
  # g++4.9
  - if [ "$CXX" = "g++" ]; then sudo apt-get install build-essential; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - sudo apt-get install libboost1.55-all-dev
  
build: make

notifications:
  email: false

os:
  - linux
