language: cpp

compiler:
  - g++
  
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y libpopt-dev libtinyxml2-dev libboost1.55-all-dev; fi
  
os:
  - linux
